### PR TITLE
Fix add and sub overflows

### LINKED ISSUE #20: Tests are broken on debug builds
More overflow-related failure:

```
$ cargo test                              
   Compiling ffv1 v0.0.0 (/home/arun/code/misc/ffv1)
    Finished test [unoptimized + debuginfo] target(s) in 0.61s
     Running unittests (target/debug/deps/ffv1-1364b031eaa6b614)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/decode.rs (target/debug/deps/decode-0024f3ae37f50235)

running 3 tests
test test_bgr0 ... FAILED
test test_gbrp16le ... FAILED
test test_yuv420 ... ok

failures:

---- test_bgr0 stdout ----
thread 'test_bgr0' panicked at 'attempt to subtract with overflow', src/jpeg2000rct.rs:34:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_gbrp16le stdout ----
thread 'test_gbrp16le' panicked at 'attempt to subtract with overflow', src/jpeg2000rct.rs:104:29


failures:
    test_bgr0
    test_gbrp16le

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.30s
```

### PR DESCRIPTION
**Pull request by Luni-4**
This PR fixes #20

### CODE REVIEW

**Comment by Luni-4** [comment]
@ford-prefect 

Please review this PR you too :)

I couldn't add you as a reviewer, I don't know why

**Comment by sdroege** [comment]
Should all that actually be wrapping, or should it rather be saturating instead? Also this all seems a bit dubious for a lossless codec so this should probably also be double-checked with the spec

**Comment by lu-zero** [comment]
When the condition happens? also +1 on being strange being wrapping_sub instead of saturating.

**Comment by Luni-4** [comment]
Using `saturating_sub` causes the tests to fail and this is the specific https://www.ffmpeg.org/~michael/ffv1.html#jpeg2000-rct

```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/decode.rs (target/debug/deps/decode-9fcaeae4872fabcb)

running 3 tests
test test_bgr0 ... FAILED
test test_yuv420 ... ok
test test_gbrp16le ... FAILED

failures:

---- test_bgr0 stdout ----
thread 'test_bgr0' panicked at 'assertion failed: `(left == right)`
  left: `(106, 106, 122)`,
 right: `(81, 115, 131)`: pixel 0', tests/decode.rs:140:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_gbrp16le stdout ----
thread 'test_gbrp16le' panicked at 'assertion failed: `(left == right)`
  left: `27385`,
 right: `29551`: pixel 0', tests/decode.rs:161:9


failures:
    test_bgr0
    test_gbrp16le

test result: FAILED. 1 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.39s

error: test failed, to rerun pass '-p ffv1 --test decode'
```

**Comment by lu-zero** [comment]
And the spec does not mention that at all...

**Comment by Luni-4** [comment]
Most recent ones https://github.com/FFmpeg/FFV1/blob/master/ffv1.md#rgb and https://datatracker.ietf.org/doc/draft-ietf-cellar-ffv1-v4/

**Comment by ford-prefect** [comment]
I guess this line...

>   Cb and Cr are positively offset by "1 << bits_per_raw_sample" after
>   the conversion from RGB to the modified YCbCr and are negatively
>   offseted by the same value before the conversion from the modified
>   YCbCr to RGB, in order to have only non-negative values after the
>   conversion.

... suggests that wrapping is in fact correct?

**Comment by Luni-4** [comment]
Yeah, it seems so. I propose to land as-is for now and modify the code at a later time

**Comment by lu-zero** [comment]
Mention the spec section and remove the comments now that is in the spec and land it :)

**Pull request merged**
